ALTER TABLE ORDERS DROP foreign key OC1;
ALTER TABLE ORDERS DROP foreign key OI1;
ALTER TABLE ORDERS DROP primary key;
ALTER TABLE ORDERS ADD primary key(Order_no,Customer_id,Item_id);

ALTER TABLE ORDERS ADD CONSTRAINT OC1 FOREIGN KEY (Customer_id) REFERENCES CUSTOMER(Customer_id);

ALTER TABLE ORDERS ADD CONSTRAINT OI1 FOREIGN KEY (Item_id) REFERENCES ITEM(Item_id);




